include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_MTK_LEDS) := leds.o
#### lenovo-sw wuwl10 20150319 for RGB LED sn3193 begin  ###
obj-$(CONFIG_LEDS_SN3193) += leds_sn3193.o
#### lenovo-sw wuwl10 20150319 for RGB LED sn3193 end    ###
